# -*- coding: utf-8 -*-
"""TF-IDF-Anatomy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FYl7xYnxdvKSAv5g-26qSJktdOqlIE9

# 1. Kütüphanelerin yüklenmesi
"""

import math
import sys
import warnings
warnings.filterwarnings('ignore')

"""# 2. Temel Python Uygulaması"""

small_docs = [
    "hasan evde uyuyor",
    "kedi ve köpek birlikte oynuyor",
    "evde kedilerim var",
    "ata köpeklerle oynuyor"
]

def tokenize(text):
  return text.lower().split()

tokenize_low = [tokenize(docs) for docs in small_docs]
print("Tokenize edilmiş dökümanlar")
for i, docs in enumerate(tokenize_low):
  print(f" Döküman {i+1}: {docs}")

def tf(term, tokenize_doc):
  count = tokenize_doc.count(term)
  return count / len(tokenize_doc) if len(tokenize_doc) > 0 else 0

def idf(term, tokenize_dokumanlar):
  doc_count = sum(1 for doc in tokenize_dokumanlar if term in doc)
  return math.log(len(tokenize_dokumanlar) / (1 + doc_count)) + 1

print("TF-IDF Değerleri:\n")
for i, doc in enumerate(tokenize_low):
  print(f"--- Döküman {i+1}: ' {small_docs[i]}' ---")
  for term in sorted(set(doc)):
    tf_val = tf(term,doc)
    idf_val = idf(term, tokenize_low)
    tfidf_val = tf_val * idf_val
    print(f" '{term}' -> TF: {tf_val:.4f}, IDF: {idf_val:.4f}, TF-IDF: {tfidf_val:.4f}")
  print()

"""# 3. Scikit-learn ile TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

vectorizer = TfidfVectorizer()
tfidf_matrisi = vectorizer.fit_transform(small_docs)

df = pd.DataFrame(
    tfidf_matrisi.toarray(),
    columns = vectorizer.get_feature_names_out(),
    index=[f"Doküman {i+1}" for i, doc in enumerate(small_docs)]
)
df

print("Her Dokümanda En Yüksek TF-IDF Skoruna Sahip Kelime:\n")
for i, doc in enumerate(small_docs):
    satir = df.iloc[i]
    en_iyi = satir.idxmax()
    skor = satir.max()
    print(f"Doküman {i+1}: '{doc}'")
    print(f"  -> En önemli kelime: '{en_iyi}' (skor: {skor:.4f})\n")

"""# 4. Görselleştirme Tarafı"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15,6))
sns.heatmap(df, annot=True, cmap="YlOrRd", fmt=".3f", linewidths=0.5)
plt.title("TF-IDF MATRİSİ (Isı Haritası)")
plt.xlabel("Kelimeler")
plt.ylabel("Dökümanlar")
plt.tight_layout()
plt.show()

"""# 5. TF-IDF'in Limitlerini Anlamak ve Sektörel Analiz

## 5.1 Anlamsal İlişki Eksikliği (Semantics Problem)
Sorun: TF-IDF kelimelerin eş anlamlı veya birbiriyle akraba olduğunu anlamaz. Her kelimeyi bağımsız birer sütun olarak görür. Örneğin, sistem loglarında "hata" ve "arıza" kelimeleri anlamca aynıdır ancak TF-IDF aralarındaki benzerliği 0 kabul eder.
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Senaryo: Sistem loglarındaki hata bildirimleri
dok_semantik = [
    "veritabanı bağlantısında hata oluştu",
    "veritabanı bağlantısında arıza oluştu",
    "sunucu odasında klima çalışıyor",
]

v_sem = TfidfVectorizer()
m_sem = v_sem.fit_transform(dok_semantik)
df_sem = pd.DataFrame(
    m_sem.toarray(),
    columns=v_sem.get_feature_names_out(),
    index=["Log 1 (Hata)", "Log 2 (Arıza)", "Log 3 (Alakasız)"],
)

print("--- TF-IDF Semantik Vektör Matrisi ---")
display(df_sem)

# Benzerlik Analizi
benzerlik = cosine_similarity(m_sem[0:1], m_sem[1:3])[0]
print(f"\n'Hata' vs 'Arıza' Log Benzerliği: {benzerlik[0]:.4f}")
print(f"'Hata' vs 'Klima' Log Benzerliği: {benzerlik[1]:.4f}")
print(
    "\n[Analiz]: 'Hata' ve 'Arıza' aslında aynı problemi anlatıyor ama TF-IDF aradaki anlam bağını kuramıyor!"
)

# Karşılaştırma: Kral ve Hükümdar gibi eş anlamlılar
dok_es_anlam = [
    "kral ülkeyi yönetir taç giyer",
    "hükümdar ülkeyi yönetir taç giyer",
    "balık denizde yüzer",
]

v2 = TfidfVectorizer()
m2 = v2.fit_transform(dok_es_anlam)

b = cosine_similarity(m2[0:1], m2[1:3])[0]
print(f"'kral ülkeyi yönetir taç giyer' vs 'hükümdar ...' : {b[0]:.4f}")
print(f"'kral ülkeyi yönetir taç giyer' vs 'balık ...'    : {b[1]:.4f}")
print()
print("Kral ve hükümdar aynı anlama gelir ancak farklı kelimelerdir.")
print("TF-IDF bunu yakalamakta zorlanır. Word2Vec gibi yöntemler")
print("bu kelimelerin benzer bağlamlarda geçtiğini öğrenip yakın vektörler üretir.")

"""## 5.2 Bağlam ve Kelime Sırası Problemi (Context & Word Order)
Sorun: TF-IDF kelimelerin dizilim sırasına bakmaz. Kelimeleri bir çuvala atıp saydığı için, eylemin yönü veya mantığı değişse bile iki metni tamamen aynı görebilir
"""

# Senaryo: Yetkilendirme logları (Kimin kimi engellediği kritik bir bilgidir)
dok_baglam = [
    "admin kullanıcıyı engelledi",
    "kullanıcı admini engelledi",
    "sistem yedekleme işlemi tamamlandı",
]

v_bag = TfidfVectorizer()
m_bag = v_bag.fit_transform(dok_baglam)
df_bag = pd.DataFrame(
    m_bag.toarray(),
    columns=v_bag.get_feature_names_out(),
    index=["Senaryo A", "Senaryo B", "Senaryo C"],
)

b_bag = cosine_similarity(m_bag[0:1], m_bag[1:3])[0]

print("--- TF-IDF Bağlam Vektör Matrisi ---")
display(df_bag)

print(f"\nSenaryo A vs Senaryo B Benzerliği: {b_bag[0]:.4f}")
print(
    "\n[Analiz]: İlk iki senaryo güvenlik açısından taban tabana zıt durumlardır."
)
print(
    "Ancak TF-IDF kelime sırasını kaybettiği için bu iki logu %100 aynı (1.0000) kabul eder!"
)

"""## 5.3 Kısmi Çözüm: N-Gram (Bigram) Kullanımı
Sorun: Kelime sırası problemini geleneksel yöntemlerle çözmek için kelimeleri ikişerli gruplar halinde (Bigram) analiz edebiliriz. Bu, kelime sırasını bir nebze kurtarır ancak veri boyutunu çok şişirir.
"""

# ngram_range=(1, 2) vererek hem tekli kelimeleri hem kelime çiftlerini alıyoruz
v_ngram = TfidfVectorizer(ngram_range=(1, 2))
m_ngram = v_ngram.fit_transform(dok_baglam)
df_ngram = pd.DataFrame(
    m_ngram.toarray(),
    columns=v_ngram.get_feature_names_out(),
    index=["Senaryo A", "Senaryo B", "Senaryo C"],
)

b_ngram = cosine_similarity(m_ngram[0:1], m_ngram[1:3])[0]

print("--- N-Gram (Bigram) TF-IDF Matrisi ---")
display(df_ngram)

print(f"\nBigram Sonrası Senaryo A vs Senaryo B Benzerliği: {b_ngram[0]:.4f}")
print(
    "\n[Analiz]: Bigram sayesinde 'admin kullanıcıyı' ve 'kullanıcı admini' farklı sütunlar oldu."
)
print(
    "Benzerlik skoru düştü ve sistem sırayı fark etti. Ancak anlamsal körlük hala devam ediyor!"
)

"""## 5.4 Boyutlanabilirlik ve Seyreklik (Scalability & Sparsity)
Sorun: Kurumsal sistemlerde (örneğin binlerce log satırında) benzersiz kelime sayısı (sözlük) on binleri bulur. Her log satırı sadece 3-5 kelimeden oluştuğu için, matrisin neredeyse tamamı sıfırlarla dolar. Bu durum hafıza (RAM) verimsizliğine ve "Boyut Lanetine" sebep olur.

Sektörel Gerçeklik: 50.000 farklı kelimenin geçtiği bir log veri havuzunda, her log satırında sadece 5 kelime varsa tablonun %99.9'u sıfır olacaktır. Sektör bu yüzden RAM israfını önlemek adına içi tamamen dolu, sabit boyutlu (örn: 384 veya 768 boyutlu) Dense (Yoğun) Vektörler yani Embedding modelleri (BERT, LLM) kullanır.
"""

import numpy as np

print("=" * 70)
print("PROBLEM 3: Boyutlanabilirlik ve Seyreklik (Scalability & Sparsity)")
print("=" * 70)

np.random.seed(42)

sistem_log_kelimeleri = [
    "error", "warn", "info", "debug", "fatal", "trace", "exception",
    "nullpointer", "timeout", "connection", "database", "query", "select",
    "insert", "update", "delete", "postgresql", "mongodb", "redis", "cache",
    "spring", "boot", "java", "maven", "dependency", "bean", "context",
    "microservice", "gateway", "eureka", "feign", "client", "request", "response",
    "controller", "service", "repository", "entity", "dto", "mapping",
    "docker", "container", "kubernetes", "pod", "deployment", "service", "ingress",
    "jenkins", "pipeline", "cicd", "git", "github", "commit", "push",
    "kafka", "rabbitmq", "message", "queue", "producer", "consumer", "topic",
    "security", "auth", "jwt", "token", "login", "logout", "permission",
    "role", "admin", "user", "server", "cloud", "aws", "azure",
    "linux", "ubuntu", "kernel", "memory", "cpu", "ram", "disk",
    "thread", "pool", "concurrency", "async", "sync", "lock", "deadlock",
    "heap", "garbage", "collector", "oom", "overflow", "stack", "trace",
    "network", "port", "ip", "address", "dns", "http", "https",
    "ssl", "tls", "certificate", "handshake", "api", "rest", "graphql",
    "json", "xml", "parser", "serialization", "deserialization", "jackson",
    "log4j", "logback", "slf4j", "metric", "prometheus", "grafana", "dashboard",
    "alert", "incident", "production", "stage", "development", "local", "environment",
    "config", "properties", "yaml", "profile", "active", "routing",
    "load", "balancer", "nginx", "proxy", "cluster", "node", "replica",
    "health", "check", "liveness", "readiness", "probe", "uptime", "downtime",
    "latency", "throughput", "performance", "optimization", "index", "sharding",
    "backup", "restore", "recovery", "failover", "cluster", "master", "slave",
    "migration", "liquibase", "flyway", "schema", "table", "column",
    "transaction", "rollback", "commit", "isolation", "level", "read",
    "write", "lock", "deadlock", "timeout", "retry", "fallback", "circuit",
    "breaker", "resilience4j", "hystrix", "dashboard", "monitor", "tracing", "zipkin",
    "sleuth", "otel", "opentelemetry", "collector", "agent", "hub", "node"
]

# Büyük veri seti simülasyonu: Sistemde akan 10.000 satırlık log havuzu oluşturuyoruz
NUM_DOCS = 10000
buyuk_log_dokumanlari = []

for _ in range(NUM_DOCS):
    # Her bir log satırı rastgele 20 ila 100 kelime uzunluğunda karmaşık bir çıktı üretsin
    log_uzunlugu = np.random.randint(20, 100)
    tek_log = " ".join(np.random.choice(sistem_log_kelimeleri, log_uzunlugu, replace=True))
    buyuk_log_dokumanlari.append(tek_log)

print(f"Simüle Edilen Toplam Log Satırı Sayısı: {len(buyuk_log_dokumanlari)}")
print(f"Örnek Bir Sistem Logu Çıktısı: '{buyuk_log_dokumanlari[0][:120]}...'")
print(f"Sistem Sözlüğündeki Benzersiz Teknik Kelime Sayısı: {len(sistem_log_kelimeleri)} kelime")

# Seyreklik ölçümü
print("Seyreklik (Sparsity) Analizi:\n")

v5 = TfidfVectorizer()
m5 = v5.fit_transform(buyuk_log_dokumanlari)

vocab_size = m5.shape[1]
toplam_hucre = m5.shape[0] * m5.shape[1]
sifir_olmayan = m5.nnz
seyreklik = 100 * (1 - sifir_olmayan / toplam_hucre)

print(f"Kelime dağarcığı boyutu (vocabulary size): {vocab_size}")
print(f"Doküman sayısı: {m5.shape[0]}")
print(f"Matris boyutu: {m5.shape}")
print(f"Toplam hücre sayısı: {toplam_hucre:,}")
print(f"Sıfır olmayan hücre sayısı: {sifir_olmayan:,}")
print(f"Seyreklik yüzdesi: %{seyreklik:.2f}")
print()
print(f"Her dokümanda ortalama sıfır olmayan öznitelik: {sifir_olmayan / m5.shape[0]:.1f}")
print(f"Her dokümanda ortalama sıfır (gereksiz) öznitelik: {(toplam_hucre - sifir_olmayan) / m5.shape[0]:.1f}")

# Seyrekliğin vocabulary büyüklüğü ile ilişkisi
print("Vocabulary Büyüklüğüne Karşı Seyreklik:\n")

max_features_degerleri = [500, 2000, 5000, 10000, 20000]
seyreklikler = []
boyutlar = []

for mf in max_features_degerleri:
    v = TfidfVectorizer(max_features=mf)
    m = v.fit_transform(buyuk_log_dokumanlari)
    toplam = m.shape[0] * m.shape[1]
    nnz = m.nnz
    sey = 100 * (1 - nnz / toplam)
    seyreklikler.append(sey)
    boyutlar.append(m.shape[1])
    print(f"  max_features={mf:5d} -> gerçek boyut={m.shape[1]:5d}, seyreklik=%{sey:.2f}")

# Görselleştir
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(boyutlar, seyreklikler, marker='o', linewidth=2)
axes[0].set_xlabel("Vocabulary Boyutu")
axes[0].set_ylabel("Seyreklik (%)")
axes[0].set_title("Vocabulary Boyutu vs Seyreklik")
axes[0].grid(True)
axes[0].set_ylim(95, 100)

axes[1].bar([str(b) for b in boyutlar], seyreklikler, color='coral')
axes[1].set_xlabel("Vocabulary Boyutu")
axes[1].set_ylabel("Seyreklik (%)")
axes[1].set_title("Vocabulary Büyüdükçe Seyreklik Artar")
axes[1].set_ylim(95, 100)
for i, v in enumerate(seyreklikler):
    axes[1].text(i, v + 0.2, f"%{v:.1f}", ha='center')

plt.tight_layout()
plt.show()

# Hafıza kullanımı karşılaştırması: Seyrek vs Yoğun matris
print("Hafıza Kullanımı: Seyrek (Sparse) vs Yoğun (Dense) Matris\n")

v6 = TfidfVectorizer(max_features=5000)
m_sparse = v6.fit_transform(buyuk_log_dokumanlari)

# Hafıza hesaplamaları
# Sparse matris: nnz * (8 byte + 4 byte + 4 byte) ≈ nnz * 16 byte
sparse_memory = m_sparse.nnz * 16 / (1024 * 1024)

# Dense matris: shape[0] * shape[1] * 8 byte
dense_memory = m_sparse.shape[0] * m_sparse.shape[1] * 8 / (1024 * 1024)

print(f"Matris boyutu: {m_sparse.shape[0]} x {m_sparse.shape[1]}")
print(f"  Seyrek matris hafızası: {sparse_memory:.2f} MB")
print(f"  Yoğun matris hafızası  : {dense_memory:.2f} MB")
print(f"  Tasarruf               : {dense_memory / sparse_memory:.1f}x daha az hafıza!")
print()
print(f"Eğer 1 milyon doküman olsaydı (20000 kelime dağarcığı ile):")
print(f"  Seyrek: yaklaşık ~150 MB")
print(f"  Yoğun : 1,000,000 × 20000 × 8 = 8,000 MB = 8 GB")

"""---
## 5.5 Boyut Laneti (Curse of Dimensionality)

Yüksek boyutlu (high-dimensional) seyrek vektörler, makine öğrenmesi modelleri için ciddi sorunlar yaratır:

| Sorun | Açıklama |
|---|---|
| **Mesafe anlamsızlaşır** | Yüksek boyutta tüm noktalar birbirine eşit uzaklıkta görünür |
| **Aşırı öğrenme (overfitting)** | Model gürültüyü öğrenir, genelleme yapamaz |
| **Hesaplama maliyeti** | 50.000 boyutlu vektörlerle işlem yapmak yavaştır |
| **Veri seyrekliği** | Anlamlı örüntü bulmak için çok daha fazla veri gerekir |

**Çözüm:** Dimensionality reduction (PCA, SVD) veya embedding yöntemleri (Word2Vec, BERT) ile boyut 50.000'den 100-300'e düşürülür.
"""

# Boyut laneti: Yüksek boyutta mesafelerin anlamını yitirmesi
print("Boyut Laneti Gösterimi: Yüksek Boyutta Mesafe Dağılımı\n")

from scipy.spatial.distance import pdist

np.random.seed(42)

boyutlar = [2, 5, 10, 50, 100, 500, 1000]
noktalar = 50

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

mesafe_ort = []
mesafe_std = []

for dim in boyutlar:
    # Birim hiperküpte rastgele noktalar
    data = np.random.uniform(0, 1, (noktalar, dim))
    mesafeler = pdist(data, 'euclidean')
    mesafe_ort.append(np.mean(mesafeler))
    mesafe_std.append(np.std(mesafeler))

axes[0].plot(boyutlar, mesafe_ort, marker='o', label='Ortalama Mesafe')
axes[0].fill_between(boyutlar,
                     np.array(mesafe_ort) - np.array(mesafe_std),
                     np.array(mesafe_ort) + np.array(mesafe_std),
                     alpha=0.2, label='±1 Std')
axes[0].set_xlabel("Boyut")
axes[0].set_ylabel("Öklid Mesafesi")
axes[0].set_title("Boyut Arttıkça Tüm Noktalar Birbirine Uzaklaşır")
axes[0].legend()
axes[0].grid(True)

# CV (değişim katsayısı) = std / mean → düşükse mesafeler ayırt edilemez
cv = [s / m for m, s in zip(mesafe_ort, mesafe_std)]
axes[1].plot(boyutlar, cv, marker='o', color='red')
axes[1].axhline(y=0, color='gray', linestyle='--')
axes[1].set_xlabel("Boyut")
axes[1].set_ylabel("CV (Std / Ort)")
axes[1].set_title("Boyut Arttıkça Mesafeler Ayırt Edilemez Hale Gelir")
axes[1].grid(True)

plt.tight_layout()
plt.show()

print("Yorum: Boyut arttıkça tüm noktalar birbirine benzer uzaklıkta olur.")
print("CV değeri 0'a yaklaşır → mesafeler anlamsızlaşır.")
print("TF-IDF'in 50.000 boyutlu vektörlerinde bu etki çok daha şiddetlidir.")

"""---

# 6. Final: Yoğun Vektör (Dense Embedding) ile Karşılaştırma

TF-IDF'in limitlerini somutlaştırmak için basit bir Word2Vec benzeri yaklaşımla karşılaştırma yapalım.
"""

# TF-IDF vs Basit Embedding: Benzerlik Karşılaştırması

from sklearn.decomposition import TruncatedSVD

test_docs = [
    "kral sarayda taç giydi",
    "kraliçe sarayda taç taktı",
    "masa odada duruyordu",
]

# --- TF-IDF ---
v_tfidf = TfidfVectorizer()
m_tfidf = v_tfidf.fit_transform(test_docs)
vocab = list(v_tfidf.get_feature_names_out())

print("TF-IDF Vektörleri (seyrek, yüksek boyutlu):")
print(f"  Boyut: {m_tfidf.shape[1]}")
print(f"  'kral ...' vs 'kraliçe ...' benzerlik: {cosine_similarity(m_tfidf[0:1], m_tfidf[1:2])[0][0]:.4f}")
print(f"  'kral ...' vs 'masa ...'  benzerlik: {cosine_similarity(m_tfidf[0:1], m_tfidf[2:3])[0][0]:.4f}")

# --- SVD ile yoğun vektöre dönüştürme (boyut indirgeme) ---
svd = TruncatedSVD(n_components=2, random_state=42)
m_dense = svd.fit_transform(m_tfidf)

print(f"\nSVD ile 2 boyuta indirgenmiş yoğun vektörler:")
for i, label in enumerate(["kral", "kraliçe", "masa"]):
    print(f"  {label}: ({m_dense[i][0]:.4f}, {m_dense[i][1]:.4f})")

benzerlik_dense = cosine_similarity(m_dense[0:1], m_dense[1:3])[0]
print(f"\nYoğun vektör benzerlikleri:")
print(f"  'kral' vs 'kraliçe': {benzerlik_dense[0]:.4f}")
print(f"  'kral' vs 'masa'   : {benzerlik_dense[1]:.4f}")

print(f"\nFark: Yoğunlaştırma sonrası kral-kraliçe benzerliği")
print(f"kral-masa benzerliğinden daha yüksek olabilir (ortak kelimeler sayesinde).")
print(f"Gerçek embedding yöntemleri (Word2Vec, BERT) bu ilişkiyi")
print(f"çok daha iyi öğrenir ve 0.7-0.9 arası benzerlik üretebilir.")

# Görselleştirme: 2D düzlemde kelime konumları
plt.figure(figsize=(10, 8))

etiketler = ["kral sarayda taç giydi", "kraliçe sarayda taç taktı", "masa odada duruyordu"]
renkler = ['gold', 'purple', 'gray']

plt.scatter(m_dense[:, 0], m_dense[:, 1], c=renkler, s=200, edgecolors='black', linewidth=1.5)
for i, label in enumerate(etiketler):
    plt.annotate(f"{label}", (m_dense[i, 0], m_dense[i, 1]),
                 textcoords="offset points", xytext=(0, 15), ha='center', fontsize=9)

plt.title("TF-IDF → SVD ile 2 Boyutlu Gösterim\n(Kral ve Kraliçe ortak kelimeler sayesinde daha yakın)")
plt.xlabel("Bileşen 1")
plt.ylabel("Bileşen 2")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

print("Not: Boyut indirgeme sonrası kral ve kraliçe birbirine daha yakın konumlanır.")
print("Ancak bu sadece ortak kelimelerden kaynaklanır. Gerçek semantik anlayış")
print("için Word2Vec veya BERT gibi modeller gereklidir.")

"""---

# 7. Tüm Limitlerin Özeti ve Çözüm Yolları

| Sınırlama | Sorun | Çözüm |
|---|---|---|
| **Anlamsal İlişki** | Eş anlamlı/ilişkili kelimeler farklı ID'ler | Word2Vec, GloVe, FastText |
| **Bağlam Kaybı** | Kelime sırası yok sayılır | N-gram, RNN, LSTM, Transformer |
| **Seyreklik** | Vektörlerin %99+ sıfır | Embedding (yoğun vektörler), SVD |
| **Boyut Laneti** | Yüksek boyutta mesafe/metalar anlamsız | PCA, t-SNE, UMAP |
| **Sabit Kelime Dağarcığı** | Yeni kelimeler eklenemez (OOV sorunu) | FastText (subword), BPE tokenization |

### Ne Zaman TF-IDF Kullanılır?
- Hızlı ve basit bir çözüm gerektiğinde
- Kelime sırasının kritik olmadığı görevlerde (spam tespiti, konu sınıflandırma)
- Küçük-orta ölçekli veri setlerinde
- İlk prototip / baseline model olarak

### Ne Zaman Daha Gelişmiş Yöntemler Gerekir?
- Anlamsal benzerlik önemliyse (arama, soru-cevap)
- Kelime sırası kritikse (sentiment analizi, NER, çeviri)
- Çok büyük ölçekli verilerde
- Çok dilli veya OOV kelimelerin bol olduğu durumlarda
"""